<address class="vcard"><img
alt="[Photo: group photo of the CSS working group in San Francisco]"
class="photo" src="/Style/CSS/csswg-2016.jpg" /> Contact:
<a class="fn url" href="/People/Bos/">Bert Bos</a><br />
<small><a rel="Copyright"
href="/Consortium/Legal/ipr-notice#Copyright">Copyright</a> ©
2020 <a href="/"><acronym title="World Wide Web Consortium"
>W3C</acronym><sup>®</sup></a></small></address>
