<div id="banner" class="section">
<h2>Site navigation</h2>

<form action="/Help/search">
<ul>
<li class="home"><a href="http://www.w3.org/" rel="home"><img alt="W3C"
src="http://www.w3.org/Icons/w3c_home" /></a></li>

<li><a href="/Style/CSS/" rel="bookmark" title="CSS home page">CSS home</a></li>

<li><a href="/Style/CSS/learning" rel="bookmark">Learn &amp; use</a></li>

<li><a href="/Style/CSS/software" rel="bookmark">Soft&shy;ware</a></li>

<li><a href="/Style/CSS/current-work" rel="bookmark"
title="Participate in the development of the CSS standard"
>Par&shy;tic&shy;i&shy;pate / <span
title="All specifications and drafts">drafts</span></a></li>

<li class="search"><input accesskey="E" id="inputField" maxlength="255"
name="q" size="10" /><button accesskey="G" type="submit" name="sa"><img
src="/2008/site/images/search-button" alt="Search"
title="Search" /></button></li>
</ul>
</form>
</div>

