<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width" />

<link rel="stylesheet" title="Main"
 media="screen, handheld, projection, tv" href="/Style/CSS/w3c-2010/main" />
<link rel="alternate stylesheet" title="Cascade"
 media="screen, handheld, projection, tv" href="/Style/CSS/floatspan-n" />
<link rel="alternate stylesheet" title="Cascade"
 media="screen, handheld, projection, tv" href="/Style/CSS/daily-color" />
<link rel="alternate stylesheet" title="Cascade (older browsers)"
 media="screen, handheld, projection, tv" href="/Style/CSS/floatspan" />
<link rel="alternate stylesheet" title="Cascade (older browsers)"
 media="screen, handheld, projection, tv" href="/Style/CSS/daily-color" />
<link rel="alternate stylesheet" title="Asymmetric"
 media="screen, handheld, projection, tv" href="/Style/CSS/asymmetric" />
<link rel="alternate stylesheet" title="Draft 3"
 media="screen, projection, tv" href="/Style/CSS/draft" />
<link rel="alternate stylesheet" title="Draft 2"
 media="screen, projection, tv" href="/Style/CSS/draft-rg" />
<link rel="stylesheet"
 media="print" href="/Style/CSS/twocolumn-print" />

<link rel="home" title="W3C" href="/" />
<link rel="top" title="CSS" href="/Style/CSS/" />
<link rel="first" title="CSS" href="/Style/CSS/" />
<link rel="last" title="The Future Of CSS (syndicator)"
 href="/Style/CSS/Planet/" />
<link rel="chapter" title="Roadmap" href="/Style/CSS/current-work" />
<link rel="chapter" title="Examples" href="/Style/Examples/007/" />
<link rel="bookmark" title="Activities" href="/Consortium/activities" />
<link rel="bookmark" title="Tech.&nbsp;reports" href="/TR/" />
<link rel="bookmark" title="Translations" href="/Consortium/Translation/" />
<link rel="bookmark" title="Software" href="/Status" />
<link rel="index" title="Site&nbsp;index" href="/Consortium/siteindex" />
<link rel="search" title="Search" href="http://search.w3.org/" />
<link rel="copyright" title="Copyright"
 href="/Consortium/Legal/ipr-notice.html#Copyright" />
<link rev="made" href="mailto:bert@w3.org%20(Bert%20Bos)" /><!-- HTML 3.2 -->
<link rel="author" href="mailto:bert@w3.org%20(Bert%20Bos)" /><!-- HTML 5 -->
