<?php
echo "<div class=\"section\" id=\"intro\">\n";
echo "<p>This is a page from the <a href=\"", esc_attr(home_url()), "\"\n";
echo "><strong>", esc_html(get_bloginfo('description')), ".</strong></a>\n";
echo "Some other places to find information are the\n";
echo "<a href=\"/Style/CSS/current-work\">“current work” page,</a>\n";
echo "the <a href=\"http://lists.w3.org/Archives/Public/www-style/\"\n";
echo ">www-style mailing list,</a> the <a href=\"/Style/CSS/Planet/\"\n";
echo ">Future of CSS</a> syndicator, and the <a\n";
echo "href='https://github.com/w3c/csswg-drafts/issues'>issue list</a> on\n";
echo "Github.</p>\n\n";

echo "<p>Do you want to know how the <a href=\"/Style/CSS/members\"\n";
echo ">CSS WG</a> works? <a\n";
echo "href=\"http://fantasai.inkedblade.net/contact\">Fantasai</a>\n";
echo "has written <a\n";
echo "href=\"http://fantasai.inkedblade.net/weblog/2011/inside-csswg/\"\n";
echo "><cite>about:csswg, An Inside View of the CSS Working Group at\n";
echo "W3C.</cite></a></p>\n";
echo "</div>\n\n";
